#!/usr/bin/env bash

LIST=(
        3sum
        4sum
        add-two-numbers
        advantage-shuffle
        AVLTree
        balanced-binary-tree
        best-time-to-buy-and-sell-stock
        best-time-to-buy-and-sell-stock-ii
        best-time-to-buy-and-sell-stock-iii
        best-time-to-buy-and-sell-stock-iv
        best-time-to-buy-and-sell-stock-with-cooldown
        best-time-to-buy-and-sell-stock-with-transaction-fee
        binary-search
        binary-search-tree-to-greater-sum-tree
        binary-tree-inorder-traversal
        binary-tree-level-order-traversal
        binary-tree-maximum-path-sum
        binary-tree-paths
        binary-tree-postorder-traversal
        binary-tree-preorder-traversal
        binary-tree-right-side-view
        binary-tree-vertical-order-traversal
        binary-tree-zigzag-level-order-traversal
        binary-trees-with-factors
        BinarySearchTree
        buildings-with-an-ocean-view
        burst-balloons
        candy
        capacity-to-ship-packages-within-d-days
        car-pooling
        climbing-stairs
        coin-change
        combination-sum
        combination-sum-ii
        combinations
        construct-binary-tree-from-inorder-and-postorder-traversal
        construct-binary-tree-from-preorder-and-inorder-traversal
        construct-binary-tree-from-preorder-and-postorder-traversal
        container-with-most-water
        convert-bst-to-greater-tree
        corporate-flight-bookings
        count-complete-tree-nodes
        count-of-range-sum
        count-of-smaller-numbers-after-self
        count-servers-that-communicate
        delete-node-in-a-bst
        diameter-of-binary-tree
        fibonacci-number
        find-all-anagrams-in-a-string
        find-and-replace-in-string
        find-duplicate-subtrees
        find-first-and-last-position-of-element-in-sorted-array
        find-largest-value-in-each-tree-row
        find-the-index-of-the-first-occurrence-in-a-string
        find-the-losers-of-the-circular-game
        first-missing-positive
        flatten-binary-tree-to-linked-list
        form-array-by-concatenating-subarrays-of-another-array
        gas-station
        generalized-abbreviation
        GraphAdjacencyList
        GraphAdjacencyMatrix
        group-anagrams
        guess-numbers
        Heap
        house-robber
        house-robber-ii
        house-robber-iii
        insert-delete-getrandom-o1
        insert-interval
        insert-into-a-binary-search-tree
        interleaving-string
        intersection-of-two-linked-lists
        invert-binary-tree
        jump-game-ii
        koko-eating-bananas
        kth-largest-element-in-an-array
        kth-smallest-element-in-a-bst
        largest-rectangle-in-histogram
        lfu-cache
        linked-list-cycle
        linked-list-cycle-ii
        longest-consecutive-sequence
        longest-palindromic-substring
        longest-substring-without-repeating-characters
        lowest-common-ancestor-of-a-binary-search-tree
        lowest-common-ancestor-of-a-binary-tree
        matrix-diagonal-sum
        maximize-distance-to-closest-person
        maximum-absolute-sum-of-any-subarray
        maximum-binary-tree
        maximum-candies-allocated-to-k-children
        maximum-depth-of-binary-tree
        maximum-subarray
        median-of-two-sorted-arrays
        merge-intervals
        merge-k-sorted-lists
        merge-sorted-array
        merge-two-binary-trees
        merge-two-sorted-lists
        middle-of-the-linked-list
        minimize-maximum-of-array
        minimum-depth-of-binary-tree
        minimum-jumps-to-reach-home
        minimum-time-to-complete-trips
        minimum-time-to-repair-cars
        minimum-window-substring
        move-pieces-to-obtain-a-string
        move-zeroes
        n-queens
        n-queens-ii
        na-ying-bi
        nth-magical-number
        number-of-ways-of-cutting-a-pizza
        number-of-ways-to-buy-pens-and-pencils
        NUPfPr
        open-the-lock
        palindrome-linked-list
        palindrome-number
        partition-equal-subset-sum
        partition-list
        pascals-triangle
        path-sum
        path-sum-ii
        permutation-in-string
        permutations
        permutations-ii
        pizza-with-3n-slices
        populating-next-right-pointers-in-each-node
        product-of-array-except-self
        random-pick-with-blacklist
        random-pick-with-weight
        range-addition
        range-sum-query-2d-immutable
        range-sum-query-immutable
        remove-duplicate-letters
        remove-duplicates-from-sorted-array
        remove-duplicates-from-sorted-list
        remove-duplicates-from-sorted-list-ii
        remove-element
        remove-k-digits
        remove-nth-node-from-end-of-list
        repeated-dna-sequences
        reverse-linked-list
        reverse-linked-list-ii
        reverse-nodes-in-k-group
        reverse-pairs
        reverse-string
        rotate-image
        rotate-list
        same-tree
        search-in-a-binary-search-tree
        search-insert-position
        serialize-and-deserialize-binary-tree
        smallest-rotation-with-highest-score
        smallest-subsequence-of-distinct-characters
        smallest-subtree-with-all-the-deepest-nodes
        sort-an-array
        spiral-matrix
        spiral-matrix-ii
        split-array-largest-sum
        subarray-sum-equals-k
        subsets
        subsets-ii
        subtract-the-product-and-sum-of-digits-of-an-integer
        sum-root-to-leaf-numbers
        summary-ranges
        super-egg-drop
        SwiftAlgorithm-Package
        symmetric-tree
        trapping-rain-water
        two-sum
        two-sum-ii-input-array-is-sorted
        unique-binary-search-trees
        unique-binary-search-trees-ii
        valid-parentheses
        validate-binary-search-tree
        xoh6Oh
        xx4gT2
        zigzag-conversion
)

for problem in "${LIST[@]}"; do
    echo "xcodebuild build -scheme $problem -destination generic/platform=macOS -configuration Debug -parallelizeTargets -quiet > /dev/null 2>&1"
    xcodebuild build -scheme $problem -destination generic/platform=macOS -configuration Debug -parallelizeTargets -quiet > /dev/null 2>&1
done
